export enum AuditAction {
  DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED",
  DOCUMENT_DOWNLOADED = "DOCUMENT_DOWNLOADED",
  DOCUMENT_PERMANENTLY_DELETED = "DOCUMENT_PERMANENTLY_DELETED",

  DOCUMENT_SHARED = "DOCUMENT_SHARED",

  VERSION_CREATED = "VERSION_CREATED",
  VERSION_RESTORED = "VERSION_RESTORED",
  VERSION_DOWNLOADED = "VERSION_DOWNLOADED",

  TAG_ADDED = "TAG_ADDED",
  TAG_REMOVED = "TAG_REMOVED",
}
